site:
    title: My Learning Environment
    url: https://docs.demo.com

content:
    sources:
    - url:
        start_path: docs
        branches: HEAD
ui:
    bundle:
        url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
        snapshot: true
    supplemental_files: ../supplemental_ui
