site:
    title: My Learning Environment
    url: https://docs.demo.com
    start_page: modules::index.adoc
content:
    sources:
    - url: https://github.com/priv-volk/my-learning-environment.git
    branches: HEAD
    start_path:  ./modules/
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
